export {default as b1} from "./1.svg"
export {default as b2} from "./2.svg"
export {default as b3} from "./3.svg"
export {default as b4} from "./4.svg"
export {default as b5} from "./5.svg"
export {default as b6} from "./6.svg"
export {default as b7} from "./7.svg"
export {default as b8} from "./8.svg"
export {default as flag} from "./flag.svg"
export {default as bomb} from "./bomb.svg"
export {default as bombFalse} from "./bomb-false.svg"
export {default as smileNorm} from "./smile-norm.svg"
export {default as smileDeath} from "./smile-death.svg"
export {default as smileWin} from "./smile-win.svg"
export {default as smileWow} from "./smile-wow.svg"


